apiVersion: 1

datasources:
  - name: InfluxDB
    type: influxdb
    access: proxy
    url: http://influxdb:8086
    jsonData:
      version: Flux
      organization: corredor
      defaultBucket: k6
      tlsSkipVerify: true
    secureJsonData:
      token: corredor-influx-token
    isDefault: true
