#!/bin/sh
# Corredor CRM — MinIO bucket initializer
# Runs once via the minio-init service in docker-compose.yml
# Creates the three required buckets if they don't already exist.

set -e

MINIO_ENDPOINT="http://minio:9000"
MINIO_ROOT_USER="${MINIO_ROOT_USER:-minioadmin}"
MINIO_ROOT_PASSWORD="${MINIO_ROOT_PASSWORD:-minioadmin}"
ALIAS="local"

echo "Waiting for MinIO to be ready..."
until mc alias set "$ALIAS" "$MINIO_ENDPOINT" "$MINIO_ROOT_USER" "$MINIO_ROOT_PASSWORD" 2>/dev/null; do
  sleep 2
done

echo "MinIO is ready. Creating buckets..."

# media — user-uploaded images, videos, and property photos
mc mb --ignore-existing "$ALIAS/media"

# documents — lease agreements, contracts, PDFs
mc mb --ignore-existing "$ALIAS/documents"

# exports — CSV/XLSX/PDF report exports generated by the worker
mc mb --ignore-existing "$ALIAS/exports"

echo "Buckets created:"
mc ls "$ALIAS"

echo "MinIO init complete."
