name: Production Deploy

on:
  push:
    branches:
      - main

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - run: echo "CI"

  deploy:
    needs: ci
    runs-on: ubuntu-latest
    steps:
      - run: echo "Deploy"
